# Generated by Django 4.2.13 on 2024-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
